//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace URL_Parser.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("URL_Parser.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URL Parser is shutting down..
        /// </summary>
        internal static string ApplicationShutdownMessage {
            get {
                return ResourceManager.GetString("ApplicationShutdownMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting URL Parser Application..
        /// </summary>
        internal static string ApplicationStartupMessage {
            get {
                return ResourceManager.GetString("ApplicationStartupMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [URL Parser] Unhandled exception in application.
        /// </summary>
        internal static string ErrorNotifiedEmailSubject {
            get {
                return ResourceManager.GetString("ErrorNotifiedEmailSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Received image parsing request for {0}..
        /// </summary>
        internal static string ReceivedParcingRequestMessageForImages {
            get {
                return ResourceManager.GetString("ReceivedParcingRequestMessageForImages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Received word parsing request for {0} URL with a {1} limit..
        /// </summary>
        internal static string ReceivedParcingRequestMessageForWords {
            get {
                return ResourceManager.GetString("ReceivedParcingRequestMessageForWords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to get headers from URL..
        /// </summary>
        internal static string UnableToGetHeaderError {
            get {
                return ResourceManager.GetString("UnableToGetHeaderError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to sent unhandled exception notification email..
        /// </summary>
        internal static string UnableToSendEmailError {
            get {
                return ResourceManager.GetString("UnableToSendEmailError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unhandled exception in Web API component of URL Parser..
        /// </summary>
        internal static string UnhandledExceptionError {
            get {
                return ResourceManager.GetString("UnhandledExceptionError", resourceCulture);
            }
        }
    }
}
